name: GitHub Actions Demo
on:
  push:
    branches:
    - main
    - release/*
    paths-ignore: [.github/**]
  pull_request:
    branches: 
    - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
